
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AppStepper': typeof import("../components/app/AppStepper.vue")['default']
    'AppCustomRadiosWithIcon': typeof import("../components/app/CustomRadiosWithIcon.vue")['default']
    'AppFilterServices': typeof import("../components/app/FilterServices.vue")['default']
    'AppFilters': typeof import("../components/app/Filters.vue")['default']
    'AppFooter': typeof import("../components/app/Footer.vue")['default']
    'AppHeader': typeof import("../components/app/Header.vue")['default']
    'AppWelcomePopup': typeof import("../components/app/WelcomePopup.vue")['default']
    'BlogsCard': typeof import("../components/blogs/Card.vue")['default']
    'BlogsSearch': typeof import("../components/blogs/Search.vue")['default']
    'CartConfirmation': typeof import("../components/cart/Confirmation.vue")['default']
    'CartLocation': typeof import("../components/cart/Location.vue")['default']
    'CartPayments': typeof import("../components/cart/Payments.vue")['default']
    'CartStepper': typeof import("../components/cart/Stepper.vue")['default']
    'CartSummary': typeof import("../components/cart/Summary.vue")['default']
    'CommonLoader': typeof import("../components/common/Loader.vue")['default']
    'FaqsCategories': typeof import("../components/faqs/FaqsCategories.vue")['default']
    'ProductProduct1': typeof import("../components/product/Product1.vue")['default']
    'ProductProduct2': typeof import("../components/product/Product2.vue")['default']
    'ProductProduct3': typeof import("../components/product/Product3.vue")['default']
    'ProductProduct4': typeof import("../components/product/Product4.vue")['default']
    'ProductProduct5': typeof import("../components/product/Product5.vue")['default']
    'ProductProduct6': typeof import("../components/product/Product6.vue")['default']
    'ProductProduct7': typeof import("../components/product/Product7.vue")['default']
    'ProductProduct8': typeof import("../components/product/Product8.vue")['default']
    'ProductProduct9': typeof import("../components/product/Product9.vue")['default']
    'ServiceService1': typeof import("../components/service/Service1.vue")['default']
    'ServiceService2': typeof import("../components/service/Service2.vue")['default']
    'ServiceService3': typeof import("../components/service/Service3.vue")['default']
    'ServiceService4': typeof import("../components/service/Service4.vue")['default']
    'ServiceService5': typeof import("../components/service/Service5.vue")['default']
    'ServiceService6': typeof import("../components/service/Service6.vue")['default']
    'ServiceService7': typeof import("../components/service/Service7.vue")['default']
    'ServiceService8': typeof import("../components/service/Service8.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtScrollbar': typeof import("../node_modules/@davestewart/nuxt-scrollbar/dist/runtime/NuxtScrollbar.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAppStepper': typeof import("../components/app/AppStepper.vue")['default']
    'LazyAppCustomRadiosWithIcon': typeof import("../components/app/CustomRadiosWithIcon.vue")['default']
    'LazyAppFilterServices': typeof import("../components/app/FilterServices.vue")['default']
    'LazyAppFilters': typeof import("../components/app/Filters.vue")['default']
    'LazyAppFooter': typeof import("../components/app/Footer.vue")['default']
    'LazyAppHeader': typeof import("../components/app/Header.vue")['default']
    'LazyAppWelcomePopup': typeof import("../components/app/WelcomePopup.vue")['default']
    'LazyBlogsCard': typeof import("../components/blogs/Card.vue")['default']
    'LazyBlogsSearch': typeof import("../components/blogs/Search.vue")['default']
    'LazyCartConfirmation': typeof import("../components/cart/Confirmation.vue")['default']
    'LazyCartLocation': typeof import("../components/cart/Location.vue")['default']
    'LazyCartPayments': typeof import("../components/cart/Payments.vue")['default']
    'LazyCartStepper': typeof import("../components/cart/Stepper.vue")['default']
    'LazyCartSummary': typeof import("../components/cart/Summary.vue")['default']
    'LazyCommonLoader': typeof import("../components/common/Loader.vue")['default']
    'LazyFaqsCategories': typeof import("../components/faqs/FaqsCategories.vue")['default']
    'LazyProductProduct1': typeof import("../components/product/Product1.vue")['default']
    'LazyProductProduct2': typeof import("../components/product/Product2.vue")['default']
    'LazyProductProduct3': typeof import("../components/product/Product3.vue")['default']
    'LazyProductProduct4': typeof import("../components/product/Product4.vue")['default']
    'LazyProductProduct5': typeof import("../components/product/Product5.vue")['default']
    'LazyProductProduct6': typeof import("../components/product/Product6.vue")['default']
    'LazyProductProduct7': typeof import("../components/product/Product7.vue")['default']
    'LazyProductProduct8': typeof import("../components/product/Product8.vue")['default']
    'LazyProductProduct9': typeof import("../components/product/Product9.vue")['default']
    'LazyServiceService1': typeof import("../components/service/Service1.vue")['default']
    'LazyServiceService2': typeof import("../components/service/Service2.vue")['default']
    'LazyServiceService3': typeof import("../components/service/Service3.vue")['default']
    'LazyServiceService4': typeof import("../components/service/Service4.vue")['default']
    'LazyServiceService5': typeof import("../components/service/Service5.vue")['default']
    'LazyServiceService6': typeof import("../components/service/Service6.vue")['default']
    'LazyServiceService7': typeof import("../components/service/Service7.vue")['default']
    'LazyServiceService8': typeof import("../components/service/Service8.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtScrollbar': typeof import("../node_modules/@davestewart/nuxt-scrollbar/dist/runtime/NuxtScrollbar.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AppStepper: typeof import("../components/app/AppStepper.vue")['default']
export const AppCustomRadiosWithIcon: typeof import("../components/app/CustomRadiosWithIcon.vue")['default']
export const AppFilterServices: typeof import("../components/app/FilterServices.vue")['default']
export const AppFilters: typeof import("../components/app/Filters.vue")['default']
export const AppFooter: typeof import("../components/app/Footer.vue")['default']
export const AppHeader: typeof import("../components/app/Header.vue")['default']
export const AppWelcomePopup: typeof import("../components/app/WelcomePopup.vue")['default']
export const BlogsCard: typeof import("../components/blogs/Card.vue")['default']
export const BlogsSearch: typeof import("../components/blogs/Search.vue")['default']
export const CartConfirmation: typeof import("../components/cart/Confirmation.vue")['default']
export const CartLocation: typeof import("../components/cart/Location.vue")['default']
export const CartPayments: typeof import("../components/cart/Payments.vue")['default']
export const CartStepper: typeof import("../components/cart/Stepper.vue")['default']
export const CartSummary: typeof import("../components/cart/Summary.vue")['default']
export const CommonLoader: typeof import("../components/common/Loader.vue")['default']
export const FaqsCategories: typeof import("../components/faqs/FaqsCategories.vue")['default']
export const ProductProduct1: typeof import("../components/product/Product1.vue")['default']
export const ProductProduct2: typeof import("../components/product/Product2.vue")['default']
export const ProductProduct3: typeof import("../components/product/Product3.vue")['default']
export const ProductProduct4: typeof import("../components/product/Product4.vue")['default']
export const ProductProduct5: typeof import("../components/product/Product5.vue")['default']
export const ProductProduct6: typeof import("../components/product/Product6.vue")['default']
export const ProductProduct7: typeof import("../components/product/Product7.vue")['default']
export const ProductProduct8: typeof import("../components/product/Product8.vue")['default']
export const ProductProduct9: typeof import("../components/product/Product9.vue")['default']
export const ServiceService1: typeof import("../components/service/Service1.vue")['default']
export const ServiceService2: typeof import("../components/service/Service2.vue")['default']
export const ServiceService3: typeof import("../components/service/Service3.vue")['default']
export const ServiceService4: typeof import("../components/service/Service4.vue")['default']
export const ServiceService5: typeof import("../components/service/Service5.vue")['default']
export const ServiceService6: typeof import("../components/service/Service6.vue")['default']
export const ServiceService7: typeof import("../components/service/Service7.vue")['default']
export const ServiceService8: typeof import("../components/service/Service8.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtScrollbar: typeof import("../node_modules/@davestewart/nuxt-scrollbar/dist/runtime/NuxtScrollbar.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAppStepper: typeof import("../components/app/AppStepper.vue")['default']
export const LazyAppCustomRadiosWithIcon: typeof import("../components/app/CustomRadiosWithIcon.vue")['default']
export const LazyAppFilterServices: typeof import("../components/app/FilterServices.vue")['default']
export const LazyAppFilters: typeof import("../components/app/Filters.vue")['default']
export const LazyAppFooter: typeof import("../components/app/Footer.vue")['default']
export const LazyAppHeader: typeof import("../components/app/Header.vue")['default']
export const LazyAppWelcomePopup: typeof import("../components/app/WelcomePopup.vue")['default']
export const LazyBlogsCard: typeof import("../components/blogs/Card.vue")['default']
export const LazyBlogsSearch: typeof import("../components/blogs/Search.vue")['default']
export const LazyCartConfirmation: typeof import("../components/cart/Confirmation.vue")['default']
export const LazyCartLocation: typeof import("../components/cart/Location.vue")['default']
export const LazyCartPayments: typeof import("../components/cart/Payments.vue")['default']
export const LazyCartStepper: typeof import("../components/cart/Stepper.vue")['default']
export const LazyCartSummary: typeof import("../components/cart/Summary.vue")['default']
export const LazyCommonLoader: typeof import("../components/common/Loader.vue")['default']
export const LazyFaqsCategories: typeof import("../components/faqs/FaqsCategories.vue")['default']
export const LazyProductProduct1: typeof import("../components/product/Product1.vue")['default']
export const LazyProductProduct2: typeof import("../components/product/Product2.vue")['default']
export const LazyProductProduct3: typeof import("../components/product/Product3.vue")['default']
export const LazyProductProduct4: typeof import("../components/product/Product4.vue")['default']
export const LazyProductProduct5: typeof import("../components/product/Product5.vue")['default']
export const LazyProductProduct6: typeof import("../components/product/Product6.vue")['default']
export const LazyProductProduct7: typeof import("../components/product/Product7.vue")['default']
export const LazyProductProduct8: typeof import("../components/product/Product8.vue")['default']
export const LazyProductProduct9: typeof import("../components/product/Product9.vue")['default']
export const LazyServiceService1: typeof import("../components/service/Service1.vue")['default']
export const LazyServiceService2: typeof import("../components/service/Service2.vue")['default']
export const LazyServiceService3: typeof import("../components/service/Service3.vue")['default']
export const LazyServiceService4: typeof import("../components/service/Service4.vue")['default']
export const LazyServiceService5: typeof import("../components/service/Service5.vue")['default']
export const LazyServiceService6: typeof import("../components/service/Service6.vue")['default']
export const LazyServiceService7: typeof import("../components/service/Service7.vue")['default']
export const LazyServiceService8: typeof import("../components/service/Service8.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtScrollbar: typeof import("../node_modules/@davestewart/nuxt-scrollbar/dist/runtime/NuxtScrollbar.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
